version: '2'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec puma -C /app/config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # links:
    #   - db
    depends_on:
      - db
      - chrome
    # environment:
      # - RAILS_SYSTEM_TESTING_SCREENSHOT=inline
      # - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    # tty: true
  chrome:
    image: selenium/standalone-chrome:3.141.59-dubnium
    ports:
      - 4444:4444
  # selenium_chrome:
  #   image: selenium/standalone-chrome-debug
  #   logging:
  #     driver: none

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web