version: '2'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  web:
    build: .
    command: bundle exec puma -C /app/config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    tty: true
    environment:
      RAILS_ENV: 'production'
  selenium_chrome:
    image: selenium/standalone-chrome:3.5.3
    
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
    environment:
      SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
      
volumes:
  db-volume: