version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    
    steps:
      - checkout
      - run:
        command: |
          echo RAILS_MASTER_KEY=${RAILS_MASTER_KEY} > ~/config/master.key
      # - run:
      #     name: change database.yml
      #     command: |
      #       rm ./config/database.yml
      #       mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: build
          command: docker-compose build
          environment:
            RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: dbsetup
          command: docker-compose run web bin/rails db:create db:migrate RAILS_ENV=test RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - run:
          name: RSpec test
          command: docker-compose run web bin/rspec
          environment:
            RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      - run:
          name: docker-compose down
          command: docker-compose down