version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: docker-compose ps
          command: docker-compose ps
      - run:
          name: データベースのセットアップ
          command: docker-compose run web bin/rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          command: docker-compose exec web bin/rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down