version: 2
jobs:
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: docker-compose ps
          command: docker-compose ps
      - run:
          name: dbsetup
          command: |
            docker-compose run rails bundle install
            docker-compose run rails bundle exec rake db:create RAILS_ENV=test
            docker-compose run rails bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: rspec
          command: docker-compose run web bin/rspec      
      - run:
          name: docker-compose down
          command: docker-compose down


workflows:
  version: 2
  test:
    jobs:
      - test