version: 2
jobs:
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: docker-compose ps
          command: docker-compose ps
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
            docker-compose run web bundle install
            docker-compose build
            docker-compose restart
            docker-compose ps
            docker-compose run web bundle exec rake db:create RAILS_ENV=test
            docker-compose run web bundle exec rake db:migrate RAILS_ENV=test
            TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
            docker-compose run web bundle exec rspec --format progress \
            --out /tmp/test-results/rspec.xml \
            $TEST_FILES
      - run:
          name: docker-compose down
          command: docker-compose down
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results


workflows:
  version: 2
  test:
    jobs:
      - test