version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      environment:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    steps:
      - checkout
      - run:
          name: change database.yml
          command: |
            rm ./config/database.yml
            mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: build
          command: docker-compose build #--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - run:
          name: docker-compose up
          command: docker-compose up -d
      # - run:
      #     name: bundle install
      #     command: docker-compose run web bundle
      # - run:
      #     name: docker-compose restart
      #     command: docker-compose restart
      - run:
          name: sleep for waiting launch db
          command: sleep 3
      - run:
          name: docker-compose ps
          command: docker-compose logs
      - run:
          name: dbsetup
          command: docker-compose run web bin/rails db:create db:migrate #RAILS_ENV=test RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - run:
          name: RSpec test
          command: docker-compose exec web bin/rspec
      - run:
          name: docker-compose down
          command: docker-compose down